name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'ZSeeker/**'
      - 'zseeker_front/**'
      - 'zseeker_back/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t xkimopro/zseeker_webapp:latest .

      - name: Push Docker image
        run: |
          docker push xkimopro/zseeker_webapp:latest
